git checkout main-page -- "src/componants/layouts/pagewrapper.jsx"
git checkout main-page -- "src/componants/shared/pagetitle.jsx"
git checkout main-page -- "src/languages/hooks/usecontent.jsx"
git checkout main-page -- "src/languages/languagesContext.jsx"
git checkout main-page -- "src/languages/hooks/uselanguage.jsx"
git checkout main-page -- "src/componants/shared/alert.jsx"
git checkout main-page -- "src/componants/layouts/splashScreen.jsx"
git checkout main-page -- "src/sass/shared/splashScreen.scss"
git checkout main-page -- "src/form/util/initZodMsgs.js" 
git checkout main-page -- "src/routes"
git checkout main-page -- "src/hooks"
git checkout main-page -- "src/redux/server state/language.js"
git checkout main-page -- "src/aos"
REm git checkout main-page -- "src/form"

REM git checkout main-page -- "src/animation/home.js"
REM git checkout main-page -- "src/componants/forms/"
REM git checkout main-page -- "src/componants/loadingitems/home.jsx"
git checkout main-page -- "src/componants/sections/servicesticker.jsx"